### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by mwieher** [Clever-Name-Tech/amazon_daily_deals_scraper#1]
Hello,

Writing this as a review of the codebase, with some suggestions/requests.

Comments on amazon_daily_deals_scraper:

- first, code looks clean, easy to read, well documented in general

- the README.md is not complete, it should have the details on how to use the code, be it via importing to another python module, or running standalone somehow

- nitpick in middlewares.py, Line 44, within process_spider_exception we see a pass statement, which, while correct Python, I don't like because:
- first, the method is required to return either None or an iterable
- while, yes, using pass does fall through to Python's default, which is return None if nothing else, it does not follow form
- see also Line 29 of the same file, within process_spider_input which does return None but has more or less the same contraints
- so, I would want all methods that have the same underlying constraints to do the same thing, so I would want to change pass to return None
- similar nitpick on line 100 within process_exception again we see a pass which is not as clear as a return None
- alternately, if we prefer just calling pass then lets do it everywhere, either way, just for uniformity within the codebase

- within pipelines.py I see we are importing via the statement from itemadapter import ItemAdapter but the ItemAdapter does not seem to be used
- I did a quick glance/search through the code and don't see this being used, so I think we can delete this line

- I believe PEP8 style requests that class names should be CapitalizedLikeThis, so for example, in the file amazon_scraper.spiders.amazon_spider.py I would require that the classname be changed to AmazonSpider, and of course anywhere it gets instantiated updated.

- I would also run python -m black <all python files> to update to 100% PEP8 style

Overall this looks like very clean code, written simply, relying heavily on the scrapy library, which is perfect.

I don't see any large, cumbersome chunks of logic that would be problematic to deal with.

The most interesting method is amazonspider.parse_product() but even in that code chunk, I don't see anything that jumps out at me as needing refactoring.  I would look at, maybe, the strings within the xpath() methods, as they are pretty heavyweight and complex, and see if I can move them out of the code, maybe into a file specifically for maintaining these path-strings.  

They distract the reader from the flow of code, and could be replaced by descriptive variable names, for example:
`pr_image        = response.xpath('//*[@id="imgTagWrapperId"]//img/@src').extract_first()`
would be more readable, in my mind, like this:
`pr_image        = response.xpath(pr_image_xpath).extract_first()`  or some other descriptive variable name.  The reader does not need to care, really, about the complexity of that string, unless they are debugging that specific piece of code, and the glut of text makes it hard to just scan the code quickly.

Only thing I'm not able to do is greenlight this as functional, or not, as the README does not tell me how the developer intends this to be instantiated and/or executed.  I don't see any bugs in the code that would cause any errors, so, at a glance I would say yes it will work - but if we had a README, I could take 30s and do a quick spin and confirm it.

Other thing I would **really** want are some tests - at the very least, a single test using the Python mock library that mocks the data that the scraper would be scraping at a very minimal level - perhaps a single page, or at most 2-3 layers deep, not many items, etc.  Just enough to look like a real response from a web server, with predictable scraping results, that we can test and confirm.  This would be a green hammer if you will, confirming the functionality by actually running it; and would be quick to run as the data would be controlled and very minimal.

**Comment by adel-alaa-dp** [comment]
Hello, thanks for taking time reviewing my work.
Kindly note that all your comments/edits are applied.
